apiVersion: v1
kind: Service
metadata:
  name: product-assistant-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
  labels:
    app: product-assistant
spec:
  type: LoadBalancer
  selector:
    app: product-assistant
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
